### ISSUE TITLE
Repetitive information - governance - officers committee

### ISSUE THREAD

**Issue by orchid00** [carpentries/docs.carpentries.org#731] opened 2021-06-08 04:07 UTC
Hi

this is to point out some repetitive text that I think we can merge into one.
![EC-officers1](https://user-images.githubusercontent.com/9795785/121121178-70d09480-c862-11eb-9380-6881a9e308d2.jpg)
 
In order of appearance:
1) https://docs.carpentries.org/topic_folders/governance/executive-council.html#officers-committee
2) https://docs.carpentries.org/topic_folders/governance/executive-council.html#executive-council-officers
3) https://docs.carpentries.org/topic_folders/governance/executive-council-officers.html

I suggest to move the text from 3 into 1 
and delete 1 and 2 referenced text. What do others think? @lexnederbragt @kariljordan

**Comment by kariljordan** [comment] 2021-06-09 12:18
Hi @orchid00, I agree. That would streamline the information nicely.

**Comment by lexnederbragt** [comment] 2021-06-10 14:00
Item 1. is about the officers committee, and to my mind not a duplicate of 2. and 3. The idea behind having 2. and 3. separately is that 2. is on a page that many folks may be interested in reading, while 3. was meant as a more in-depth description for folks considering, or taking up, an officer role. In other words, 2. is for both transparency and onboarding, while 3. is onboarding only. 3. can be merged into 2. but then it becomes an even bigger wall of text...

**Comment by maneesha** [comment] 2021-06-10 19:02
@lexnederbragt @orchid00 let me know what you think of PR #733 
Otherwise I think this may necessitate re-writing and re-organizing the whole EC section.  Would someone on the EC be interested in doing this?

**Comment by maneesha** [comment] 2021-11-11 18:52
@lexnederbragt  @orchid00 
Would you like to keep this open?

**Comment by lexnederbragt** [comment] 2021-12-03 12:38
For lack of another responses than mine I propose to close this issue.

**Closed** 2021-12-03 14:29 UTC
