### ISSUE TITLE
Add font(s) and colours to Style Guide

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/docs.carpentries.org#438] opened 2019-04-30 07:23 UTC
What fonts does the Carpentries use in communications? What colour is the logo? Those kinds of things would be useful to have in the style guide too.

**Comment by maneesha** [comment] 2019-04-30 11:40
Thanks @lexnederbragt  for this suggestion.

Asking @jduckles  and @weaverbel - would you be able to help with this? I know you two led the project to develop the logo.

**Comment by jduckles** [comment] 2019-04-30 22:05
Logo as it came is Red:3	Green:21	Blue:86, since its SVG, this can always be changed as it is a simple one-colour logo design. 

Website font choices are listed here (highlighted rows): https://github.com/carpentries/carpentries.org/blob/7fe69011b98dac28ad88acb1818dfb676bbd84ce/_sass/_02_settings_typography.scss#L25-L27

As far as the logo, fonts were never stated by designer, but forensics by others indicate the logo font is "Nexa extra bold" (see below). 

![image](https://user-images.githubusercontent.com/119403/56996238-f7ccd080-6bf7-11e9-87b7-3e8695af81c9.png)

**Comment by weaverbel** [comment] 2019-05-01 01:31
Sorry, I don't know what the font was. Only the logo designer would know. @jduckles was the person who dealt with that person. I just gave it a tick ;-).

**Comment by anenadic** [comment] 2019-05-01 08:51
With regards to the logo, we could also create 4 "official" versions of logo ourselves, and ask people to use those, e.g.:
![image](https://user-images.githubusercontent.com/631719/57010745-3b263f80-6bf6-11e9-82ec-65077212dc68.png)
![image](https://user-images.githubusercontent.com/631719/57010757-49745b80-6bf6-11e9-8261-81008139dda6.png)
and the same ones in white for use on the dark backgrounds.

**Comment by jduckles** [comment] 2019-05-01 10:59
@anenadic see https://github.com/carpentries/logo

**Comment by anenadic** [comment] 2019-05-01 11:20
> @anenadic see https://github.com/carpentries/logo

Yes, those precisely (knew there was a link somewhere), thank you @jduckles. But in addition, in the style guide we should point to those and explicitly say what can and cannot be done to the logo.

**Comment by maneesha** [comment] 2019-05-01 12:13
Agreeed @anenadic 
Here's something from the Python Software Foundation we could use as an example:  https://www.python.org/community/logos/

**Comment by libcce** [comment] 2019-05-01 12:29
Here is the LC style guide by Drew Heles and David Kane if you need another example: https://github.com/LibraryCarpentry/lc-styleguide.

**Comment by anenadic** [comment] 2019-05-02 10:23
Software Sustainability Institute I work for also have a media guide: https://software.ac.uk/about/media-enquiries

**Comment by kmomar** [comment] 2020-04-15 14:58
Adding myself as an assignee and noting that I agree we should have the colors and fonts listed in the style guide. I think once we finish the logo work we can go in and add the color along with recommendations and rules around our logo usage.

**Comment by kmomar** [comment] 2020-11-16 20:24
Closing this as we now have the fonts and colors listed here: https://docs.carpentries.org/topic_folders/communications/resources/brand_identity.html. Noting also that this page will be refined with more recommendations and rules.

**Closed by kmomar** 2020-11-16 20:24 UTC
Labels: style-guide
